### ISSUE TITLE
Some problem about checkpoint files restoring

### ISSUE THREAD

**Issue by Ariuab** [lzx551402/contextdesc#15] opened 2020-01-13 14:46 UTC
When I try to restore the contextdesc/model.ckpt-400000.meta I got the error :

op_def = op_dict[node.op]
KeyError: 'ThreeNN'

and my tensorflow version is 1.14.0. 
Could you please tell me which version do you restore the model or Linux version?
Thanks! That would be very helpful!!

**Comment by lzx551402** [comment] 2020-01-14 02:43
I'm also using TF 1.14.0. It is weird to see such an error, would you provide the command you called? I cannot reproduce this problem on my machine.

**Comment by Ariuab** [comment] 2020-01-14 09:35
It's also said"tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'ThreeNN' in binary running on LAPTOP. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed"


It's seemd that we need to register the op "Threenn"    and there is the op on github
https://github.com/charlesq34/pointnet2/blob/master/tf_ops/3d_interpolation/tf_interpolate.cpp



import tensorflow as tf
with tf.Session()as sess:
    saver=tf.train.import_meta_graph("./pretrained/contextdesc/model.ckpt-400000.meta")#bug here
    saver.restore(sess,"./pretrained/contextdesc/"+"model.cptk")
    print('model restored')

**Comment by lzx551402** [comment] 2020-01-14 12:00
*.meta files contains all variables and operations that I used in training, including some that were already deprecated (e.g., ThreeNN) but not removed when releasing the code, which caused the error you report.

I won't suggest you restoring the meta graph by loading *.meta file. Instead, you may refer to our example script, and 1) rebuild the graph, 2) restore **only** the parameters in *.data-0000-of-00001 and *.index file.

**Comment by lzx551402** [comment] 2020-01-14 12:26
To avoid this confusion, I have removed *.meta files in my model releasing.

**Comment by Ariuab** [comment] 2020-01-14 13:55
Thanks!! It will be very helpful!
The tensorflow also said "Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint"

**Comment by lzx551402** [comment] 2020-01-14 14:20
Yes, again, the training graph stored in *.meta file contains some experimental operations that have been deprecated. The example script will build a clean graph to reproduce the results.

**Comment by lzx551402** [comment] 2020-02-26 13:15
I assume that this issue has been resolved, and close this thread.

**Closed by lzx551402** 2020-02-26 13:15 UTC
